# Generated by Django 3.2.4 on 2021-08-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='username',
        ),
    ]
